program jcf_test;

uses
  Forms,
  TestFramework in '..\..\..\..\..\DUnit\src\TestFramework.pas',
  GUITestRunner in '..\..\..\..\..\DUnit\src\GUITestRunner.pas' {GUITestRunner},
  WordMap in '..\..\Parse\WordMap.pas',
  BuildParseTree in '..\..\Parse\BuildParseTree.pas',
  BuildTokenList in '..\..\Parse\BuildTokenList.pas',
  ParseError in '..\..\Parse\ParseError.pas',
  ParseTreeNode in '..\..\Parse\ParseTreeNode.pas',
  SourceToken in '..\..\Parse\SourceToken.pas',
  SourceTokenList in '..\..\Parse\SourceTokenList.pas',
  TokenType in '..\..\Parse\TokenType.pas',
  fShowParseTree in '..\..\Parse\UI\fShowParseTree.pas' {frmShowParseTree},
  FileWriter in '..\..\ReadWrite\FileWriter.pas',
  CodeReader in '..\..\ReadWrite\CodeReader.pas',
  CodeWriter in '..\..\ReadWrite\CodeWriter.pas',
  Converter in '..\..\ReadWrite\Converter.pas',
  ConvertTypes in '..\..\ReadWrite\ConvertTypes.pas',
  FileConverter in '..\..\ReadWrite\FileConverter.pas',
  FileReader in '..\..\ReadWrite\FileReader.pas',
  JcfMiscFunctions in '..\..\Utils\JcfMiscFunctions.pas',
  FileUtils in '..\..\Utils\FileUtils.pas',
  JCFLog in '..\..\Utils\JcfLog.pas',
  TestFileParse in 'TestFileParse.pas',
  VisitParseTree in '..\..\Process\VisitParseTree.pas',
  BaseVisitor in '..\..\Process\BaseVisitor.pas',
  VisitSetXY in '..\..\Process\VisitSetXY.pas',
  RemoveComment in '..\..\Process\Obfuscate\RemoveComment.pas',
  ParseTreeNodeType in '..\..\Parse\ParseTreeNodeType.pas',
  RemoveUnneededWhiteSpace in '..\..\Process\Obfuscate\RemoveUnneededWhiteSpace.pas',
  FixCase in '..\..\Process\Obfuscate\FixCase.pas',
  ReduceWhiteSpace in '..\..\Process\Obfuscate\ReduceWhiteSpace.pas',
  RemoveConsecutiveWhiteSpace in '..\..\Process\Obfuscate\RemoveConsecutiveWhiteSpace.pas',
  RemoveReturn in '..\..\Process\Obfuscate\RemoveReturn.pas',
  ObfuscateControl in '..\..\Process\Obfuscate\ObfuscateControl.pas',
  RebreakLines in '..\..\Process\Obfuscate\RebreakLines.pas',
  TestObfuscate in 'TestObfuscate.pas',
  SetUses in '..\..\Settings\SetUses.pas',
  JCFSetBase in '..\..\Settings\JCFSetBase.pas',
  JCFSettings in '..\..\Settings\JCFSettings.pas',
  SetAlign in '..\..\Settings\SetAlign.pas',
  SetAnyWordCaps in '..\..\Settings\SetAnyWordCaps.pas',
  SetCaps in '..\..\Settings\SetCaps.pas',
  SetClarify in '..\..\Settings\SetClarify.pas',
  SetFile in '..\..\Settings\SetFile.pas',
  SetIndent in '..\..\Settings\SetIndent.pas',
  SetLog in '..\..\Settings\SetLog.pas',
  SetObfuscate in '..\..\Settings\SetObfuscate.pas',
  SetReplace in '..\..\Settings\SetReplace.pas',
  SetReturns in '..\..\Settings\SetReturns.pas',
  SetSpaces in '..\..\Settings\SetSpaces.pas',
  SetUi in '..\..\Settings\SetUi.pas',
  SettingsStream in '..\..\Settings\Streams\SettingsStream.pas',
  RegistrySettings in '..\..\Settings\Streams\RegistrySettings.pas',
  VersionConsts in '..\..\VersionConsts.pas';

{$R *.res}

begin
  Application.Initialize;
  GUITestRunner.RunRegisteredTests;
end.
